confirm_profile_update_link:
    path: /vendor/profile-update/{token}
    methods: [GET]
    defaults:
        _controller: bitbag_mvm_plugin.controller.confirm_profile_update_action
        _sylius:
            template: "Vendor/profileUpdate.html.twig"
            form: BitBag\OpenMarketplace\Form\Type\VendorType
            event: update                
            repository:
                method: findOneByActivationToken
                arguments:
                    token: $token
