bitbag_mvm_plugin:
    resource: |
        alias: bitbag_mvm_plugin.conversation
        section: admin
        templates: "@SyliusAdmin\\Crud"
        except: ['show', 'update', 'bulk_delete']
        redirect: index
        grid: bitbag_mvm_plugin_admin_conversation
        permission: true
        vars:
            all:
                header: bitbag_mvm_plugin.ui.conversations_listing.admin_header
                subheader: bitbag_mvm_plugin.ui.conversations_listing.admin_subheader
    type: sylius.resource
    prefix: /admin
    
bitbag_mvm_plugin_admin_conversation_create:
    path: /admin/conversation/create
    methods: [GET,POST]
    defaults:
        _controller: bitbag_mvm_plugin.controller.action.conversation.create_new_conversation_action
        _sylius:
            template: "@BitBagSyliusMultiVendorMarketplacePlugin/Admin/Conversation/create.html.twig"
            redirect: bitbag_mvm_plugin_admin_conversation_show
            mail_redirect: mvm_vendor_conversation_show
        
bitbag_mvm_plugin_admin_conversation_show:
    path: /admin/conversations/{id}
    methods: [GET,POST]
    defaults:
        _controller: bitbag_mvm_plugin.controller.conversation.conversation_controller:show
        _sylius:
            template: "@BitBagSyliusMultiVendorMarketplacePlugin/Admin/Conversation/show.html.twig"

bitbag_mvm_plugin_admin_conversation_archive:
    path: /admin/conversations/{id}/archive
    methods: [GET,POST]
    defaults:
        _controller: bitbag_mvm_plugin.controller.action.conversation.send_archive_request_action
        _sylius:
            redirect: bitbag_mvm_plugin_admin_conversation_index


bitbag_mvm_plugin_admin_conversation_message_add:
    path: /admin/conversations/{id}/message/add
    methods: [GET, POST]
    defaults:
        _controller: bitbag_mvm_plugin.controller.action.conversation_message.add_message_action
        _sylius:
            redirect: bitbag_mvm_plugin_admin_conversation_show
            mail_redirect: bitbag_mvm_plugin_admin_conversation_show
            
