sylius_shop_checkout_complete:
    path: /complete
    methods: [GET, PUT]
    defaults:
        _controller: bitbag.mvm_plugin.controller.order.order_controller:updateAction
        _sylius:
            event: complete
            flash: false
            template: '@SyliusShop/Checkout/complete.html.twig'
            repository:
                method: find
                arguments:
                - "expr:service('sylius.context.cart').getCart()"
            state_machine:
                graph: sylius_order_checkout
                transition: complete
            redirect:
                route: sylius_shop_order_pay
                parameters:
                    tokenValue: resource.tokenValue
            form:
                type: Sylius\Bundle\CoreBundle\Form\Type\Checkout\CompleteType
                options:
                    validation_groups: 'sylius_checkout_complete'
