sylius_resource:
    resources:
        bitbag_mvm_plugin.conversation_category:
            driver: doctrine/orm
            classes:
                model: BitBag\SyliusMultiVendorMarketplacePlugin\Entity\Conversation\Category
                interface: BitBag\SyliusMultiVendorMarketplacePlugin\Entity\Conversation\CategoryInterface
                repository: BitBag\SyliusMultiVendorMarketplacePlugin\Repository\Conversation\CategoryRepository
