sylius_customer:
    resources:
        customer:
#            driver: doctrine/orm
            classes:
#                model: Tests\BitBag\SyliusMultiVendorMarketplacePlugin\Entity\Conversation
#                controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
#                interface: BitBag\SyliusMultiVendorMarketplacePlugin\Entity\Conversation\ConversationInterface
                repository: BitBag\SyliusMultiVendorMarketplacePlugin\Repository\CustomerRepository
#                form: BitBag\SyliusMultiVendorMarketplacePlugin\Form\Type\Conversation\ConversationType
