sylius_resource:
    resources:
        bitbag_mvm_plugin.draft_attribute:
            classes:
                model: BitBag\SyliusMultiVendorMarketplacePlugin\Entity\ProductListing\DraftAttribute
                interface: BitBag\SyliusMultiVendorMarketplacePlugin\Entity\ProductListing\DraftAttributeInterface
                controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
#                repository: BitBag\SyliusMultiVendorMarketplacePlugin\Repository\VendorRepository
#                form: BitBag\SyliusMultiVendorMarketplacePlugin\Form\Type\VendorEditType
