sylius_order:
    resources:
        order:
            classes:
                model: Sylius\Component\Core\Model\Order
                controller: BitBag\SyliusMultiVendorMarketplacePlugin\Controller\Order\OrderController
                repository: Sylius\Bundle\CoreBundle\Doctrine\ORM\OrderRepository
                form: Sylius\Bundle\ResourceBundle\Form\Type\AbstractResourceType\OrderType
