sylius_resource:
   resources:
      bitbag_mvm_plugin.product_listing:
          driver: doctrine/orm
          classes:
              model: BitBag\SyliusMultiVendorMarketplacePlugin\Entity\ProductListing
              interface: BitBag\SyliusMultiVendorMarketplacePlugin\Entity\ProductListingInterface
