sylius_grid:
  templates:
    action:
      details: '@BitBagSyliusMultiVendorMarketplacePlugin/Grid/Action/product_details.html.twig'
      restore: '@BitBagSyliusMultiVendorMarketplacePlugin/Grid/Action/restore.html.twig'
    filter:
      product_listing_status: '@BitBagSyliusMultiVendorMarketplacePlugin/Grid/Filter/product_listing_status.html.twig'
  grids:
    bitbag_mvm_plugin_admin_product_listing:
      driver:
        name: doctrine/orm
        options:
          class: BitBag\SyliusMultiVendorMarketplacePlugin\Entity\ProductListing\ProductListing
          repository:
            method: createQueryBuilderWithLatestDraft
      sorting:
        id: desc
      filters:
        search:
          type: string
          form_options:
            type: contains
          options:
            fields: ['code']
        status:
          type: product_listing_status
          label: bitbag_mvm_plugin.ui.status
      fields:
        id:
          type: string
          label: bitbag_mvm_plugin.ui.id
          sortable: ~
        code:
          type: string
          label: bitbag_mvm_plugin.ui.code
          sortable: ~
        getLatestDraft.publishedAt:
          type: datetime
          label: bitbag_mvm_plugin.ui.published_at
          sortable: ~
        getLatestDraft.verifiedAt:
          type: datetime
          label: bitbag_mvm_plugin.ui.verified_at
          sortable: ~
        getLatestDraft.status:
          type: twig
          label: bitbag_mvm_plugin.ui.status
          sortable: ~
          options:
            template: "@BitBagSyliusMultiVendorMarketplacePlugin/Grid/Field/product_listing_status.html.twig"
      actions:
        item:
          details:
            type: details
            label: bitbag_mvm_plugin.ui.details
            options:
              link:
                route: bitbag_mvm_plugin_admin_product_listing_show
                parameters:
                  id: resource.id
          restore_visibility:
            type: restore
