sylius_grid:
    grids:
        bitbag_mvm_plugin_admin_product_listing:
            driver:
                name: doctrine/orm
                options:
                    class: BitBag\SyliusMultiVendorMarketplacePlugin\Entity\ProductListing
            fields:
                name:
                    type: string
                    label: sylius.ui.name
                publishedAt:
                    type: datetime
                    label: bitbag_mvm_plugin.ui.publishedAt
                status:
                    type: string
                    label: bitbag_mvm_plugin.ui.status
