sylius_resource:
  resources:
    bitbag_mvm_plugin.product_listing:
      driver: doctrine/orm
      classes:
        model: BitBag\OpenMarketplace\Entity\ProductListing\ProductListing
        repository: BitBag\OpenMarketplace\Repository\ProductListing\ProductListingRepository

    bitbag_mvm_plugin.product_draft:
      driver: doctrine/orm
      classes:
        model: BitBag\OpenMarketplace\Entity\ProductListing\ProductDraft
        interface: BitBag\OpenMarketplace\Entity\ProductListing\ProductDraftInterface
        controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController
        form: BitBag\OpenMarketplace\Form\ProductListing\ProductType

    bitbag_mvm_plugin.product_translation:
      driver: doctrine/orm
      classes:
        model: BitBag\OpenMarketplace\Entity\ProductListing\ProductTranslation
        interface: BitBag\OpenMarketplace\Entity\ProductListing\ProductTranslationInterface

    bitbag_mvm_plugin.product_listing_price:
      driver: doctrine/orm
      classes:
        model: BitBag\OpenMarketplace\Entity\ProductListing\ProductListingPrice
        interface: BitBag\OpenMarketplace\Entity\ProductListing\ProductListingPriceInterface

    bitbag_mvm_plugin.product_draft_image:
      driver: doctrine/orm
      classes:
        model: BitBag\OpenMarketplace\Entity\ProductListing\ProductDraftImage

    bitbag_mvm_plugin.product_draft_taxons:
      driver: doctrine/orm
      classes:
        model: BitBag\OpenMarketplace\Entity\ProductListing\ProductDraftTaxon
        interface: BitBag\OpenMarketplace\Entity\ProductListing\ProductDraftTaxonInterface
        repository: BitBag\OpenMarketplace\Repository\ProductListing\ProductDraftTaxonRepository
