bitbag_mvm_conversation_category:
    resource: |
        alias: bitbag_multi_vendor_marketplace.conversation_category
        section: admin
        except: ['show']
        templates: "@SyliusAdmin\\Crud"
        grid: conversation_category
    type: sylius.resource
    prefix: /admin
