bitbag_mvm_plugin_admin_product_listing:
    resource: |
        alias: bitbag_mvm_plugin.product_listing
        section: admin
        templates: '@SyliusAdmin/Crud'
        only: ['index']
        redirect: index
        grid: bitbag_mvm_plugin_admin_product_listing
    type: sylius.resource
